@startuml
class Solution43{
- setName (String)
- setAuthorName (String)
- setDataPath (String)
}
class Create{
+ createWebsiteName(String)
+ createHTMLWebsite(String)
+ createJSWebsite(String)
+ createCSSWebsite(String)
+ createHTML (String)
+ createFolder(void)
+ writeHTMLinput(void)
}
Solution43 -- Create
@enduml