@startuml
class Solution46{
+List<String> word
+List<String> frequentword
+List<Integer> frequencyvalue
+List<String> stringFrequency
+ main:void
+ findWord: void
- findFrequency: void
- sort: void
- getIndex: void
- display: void
}
@enduml